### ISSUE TITLE
Apparence des champs de saisie

### ISSUE THREAD

**Issue by goroh-io** [Nihilivin/CreditCalc#3]
Pour chaque champ de saisie: 
- enlever le border bleu si le champ est sous focus
- ne pas autoriser la saisie de lettres (propriété html5) 
- ne pas changer la bordure si le champ contient une valeur non parsable ou incohérente, mais changer la couleur du texte lui-même en rouge

**Comment by Nihilivin** [comment]
Le bord bleu dépend probablement du navigateur. Quel est le navigateur utilisé?

**Comment by Nihilivin** [comment]
Je ne vois pas quelle propriété HTML5 permet d'empêcher les lettres...

**Comment by goroh-io** [comment]
en html 5 il faudrait essayer le <input type="number">
border bleu non reproduit (je devais être fatigué)

**Comment by Nihilivin** [comment]
J'y avais pensé, mais le "input type=number" sera trop restrictif au niveau du formatage: eg "." au lien de ",", pas d'espaces autorisés, bref, le formatage final ne sera pas vraiment le mieux possible.
Je vais faire un filtrage des touches appuyées pour n'en autoriser que certaines. Ce me semble être l'option la plus fonctionnelle.
