### ISSUE TITLE
Erreurs d'arrondis interne ?

### ISSUE THREAD

**Issue by goroh-io** [Nihilivin/CreditCalc#4]
Dans les champs de saisie, on entre les données suivantes:
Montant  - 200 000
durée - 25
taux 2
on obtient en cliquant sur "Go" une mensualité de 847,71, ce qui est bon.
Toutefois si on clique à la suite sur le bouton des années, la durée tombe à 24 ans ce qui est faux. 
De la même façon si on clique sur le bouton du montant on retrouve 200 000,32 €, il faudrait arrondir à l'euro le plus proche

**Comment by Nihilivin** [comment]
Comme spécifié dans les specs:
> Les euros (pour le montant ou les mensualités) sont toujours exprimés en centimes, arrondis au centime supérieur, avec des espaces pour séparateurs de milliers. Le taux ne comporte de 2 chiffres après la virgule et est toujours exprimé en pourcent (doit être divisé par 100 pour les calculs). Les années sont arrondies à l'année inférieure.
La valeur réelle est 847.70867728812, affichée 847.71 (arrondi au suppérieur). Pour M:200000,T:2,P:847.71, la durée calculée est 24.999949400294163 arrondi à l'inférieur, soit 24.

Je comprend que cela donne des résultats pouvant _paraître_ incohérents, mais tout est parfaitement conforme aux spécifications

**Comment by goroh-io** [comment]
OK. il ne servirait à rien de changer la façon de calculer pour mettre à l'arrondi supérieur : la solution est de travailler sur les mensualités (qui sont la base du calcul). Il va falloir faire un tas de petites exceptions pour ce champ durée (youpi :/), je retravaille les specs en ce sens.

**Comment by Nihilivin** [comment]
Ok. Re-poste un commentaire sur ce ticket une fois les corrections effectuées stp.

**Comment by goroh-io** [comment]
Corrections faites dans les specs

> Formatage et calcul du champ durée
> Un champ “mois” est présent à droite du champ durée (entre le champ de saisie et le bouton de lancement du calcul). Visuellement aucune séparation n’existe avec le champ des années.  L’utilisateur peut saisir ce champ selon les mêmes règles que pour le champ années. Ce champ est mis à 0 si il est laissé vide. Comme pour les années, ce champ ne peut contenir que des entiers. A chaque calcul de la durée (des années) les champs années et mois sont mis à jour avec les formules suivantes :

> Années : M/12 , où M est la durée du crédit calculée, en mois, arrondi à l’entier supérieur
> Mois :  M mod (12) 
> Note: pour lever les ambiguités, l’unité “an(s)” du champ années est remplacé par “an(s) et”. Le champ mois a pour unité “mois”. (Cf design)
> Ce champ mois est pris en compte dans le calcul de la durée de crédit
