### ISSUE TITLE
Erreurs d'arrondis sur les mensualités

### ISSUE THREAD

**Issue by goroh-io** [Nihilivin/CreditCalc#8]
Le calcul de l'intérêt pour chaque mensualité (ou du capital remboursé) n'est pas arrondi au centime le plus proche, mais systématiquement au centime supérieur, ce que donne des erreurs (même minimes) sur les mensualités.
Par exemple pour un crédit à 2% sur 1 an à 350 000 € on a une mensualité calculée de 29 483,61€, et le tableau d'amortissement suivant

![image](https://cloud.githubusercontent.com/assets/19395412/15802514/21580dac-2ab5-11e6-93a7-992ab73abe00.png)

**Comment by Nihilivin** [comment]
Il faut savoir quelle donnée il faut prioriser. La mensualité est calculée et arrondie au centime suppérieure: dans ce cas, la mensualité réelle est comprise entre ]29483.60,29483.61], la valeur calculée est de 29483.603549435993 . Même en arrondissant, les valeurs fluctueront pour un total mensuel dans [29483.60,29483.61]. Enfin, le total de chaque colonne sera, quoi qu'il en soit, très probablement erroné et différente de la valeur réellement calculée, la précision étant perdue par l'usage des arrondis. C'est l'inconvénient des méthodes itératives, et je ne pense pas pouvoir faire grand chose.

Je clos ce ticket avec la modification faisant oscillier la somme mensuelle entre [x-0.01,x]

**Comment by goroh-io** [comment]
l'approximation à + ou - 1 centime est suffisante pour la v2 pour les valeurs d'intérêts et montant remboursé. Les totaux sont à calculer indépendamment (et non en faisant la somme des valeurs). Les incohérences à ce niveau sont acceptables et seront probablement rares
